-- Revisi V5 §6 — Agenda Kerja Sama replaced by documentation/data/AGENDA_KERJASAMA.csv
-- (generated from it). Every CSV row ends up active; any agenda not in the CSV
-- is deactivated, never deleted — past proposals still reference it (BR-23).
-- is_amendment stays a boolean on "Adendum/Amandemen" (BR-16).
insert into agenda (nama, is_amendment) values
  ('Tridharma Perguruan Tinggi', false),
  ('Kuliah Tamu/Guest Lecturer', false),
  ('Gelar Bersama/Joint Degree', false),
  ('Gelar Ganda/Double Degree', false),
  ('Gelar Percepatan/Fast Track', false),
  ('Student Exchange', false),
  ('Study Abroad', false),
  ('Magang/Internship', false),
  ('Immersion', false),
  ('Short Program', false),
  ('Studi Ekskursi', false),
  ('Tugas Akhir', false),
  ('Thesis Writing', false),
  ('Academic Visit', false),
  ('Academic Exchange', false),
  ('Cultural Exchange', false),
  ('Facilities Exchange', false),
  ('Staf/Faculty Exchange', false),
  ('Joint Curriculum', false),
  ('Credit Transfer', false),
  ('Joint Lecturer/ Kuliah Bersama', false),
  ('Joint Projects (Konferensi/Seminar/Workshop/Lomba/pameran)', false),
  ('Joint Research', false),
  ('Publikasi Jurnal Ilmiah', false),
  ('Merdeka Belajar Kampus Merdeka (MBKM)', false),
  ('Rekrutmen Lulusan', false),
  ('Pengabdian Kepada Masyarakat/ Service Learning', false),
  ('Beasiswa', false),
  ('Hibah/Donasi', false),
  ('Educational and Training Program', false),
  ('Sertifikasi', false),
  ('Akreditasi', false),
  ('Program Sejong Korean', false),
  ('Penerimaan mahasiswa baru', false),
  ('Pemanfaatan e-AMITRA', false),
  ('Penyelenggaraan Pusat Dukungan Teknologi dan Inovasi', false),
  ('Penyelenggaraan IELTS Off-site Testing', false),
  ('Penyelenggaraan Tax Center', false),
  ('Pelaksanaan Asesor BKD Sertifikasi Dosen', false),
  ('Pendayagunaan Aparatur Negara dan Pelaksanaan Reformasi Birokrasi', false),
  ('Pemberdayaan dan pemanfaatan perpustakaan', false),
  ('Website Bursa Informasi Pendidikan Tinggi (BIDikTi)', false),
  ('Layanan Transaksi Online', false),
  ('Asuransi', false),
  ('Penyediaan Layanan Telekomunikasi', false),
  ('Promosi Kegiatan', false),
  ('Pembuatan Website', false),
  ('Proyek pendukung untuk Penelitian', false),
  ('Perjanjian Kerahasiaan', false),
  ('Pelatihan Guru', false),
  ('Pengembangan dan kerahasiaan layanan komputasi, server, perangkat lunak, penyimpanan data, database, dan jaringan modul digital dalam Platform LMS Gamifikasi', false),
  ('Pengembangan modul digital ke dalam Platform LMS Gamifikasi', false),
  ('Pemanfaatan LMS Gamifikasi sebagai medium pembelajaran di universitas masing-masing.', false),
  ('Layanan Digital', false),
  ('Pemanfaatan Sistem Pembelajaran Petraverse', false),
  ('Pelatihan', false),
  ('Program ODP (Officer Development Program)', false),
  ('Product & Design Development Center', false),
  ('Software Application Development Center', false),
  ('Perlindungan anak, kesehatan masyarakat, sosial, ekonomi, lingkungan, kebencanaan', false),
  ('Pelayanan pendaftaran HAKI pada lingkup sektor industri yang tersedia', false),
  ('Pemanfaatan Vending Machine', false),
  ('Joint Project (Pemberian Jasa)', false),
  ('Pendirian Fakultas Kedokteran Gigi', false),
  ('Adendum/Amandemen', true),
  ('Online Course', false),
  ('Program Darmasiswa', false),
  ('Falling Walls Lab Indonesia', false),
  ('Business Class with PBS', false),
  ('Kegiatan Mata Kuliah Wajib Kurikulum (MKWK)', false),
  ('Perekrutan mahasiswa', false),
  ('Dual Degree', false)
on conflict (nama) do update
  set is_active = true, is_amendment = excluded.is_amendment;

update agenda set is_active = false
 where nama not in (
  'Tridharma Perguruan Tinggi',
  'Kuliah Tamu/Guest Lecturer',
  'Gelar Bersama/Joint Degree',
  'Gelar Ganda/Double Degree',
  'Gelar Percepatan/Fast Track',
  'Student Exchange',
  'Study Abroad',
  'Magang/Internship',
  'Immersion',
  'Short Program',
  'Studi Ekskursi',
  'Tugas Akhir',
  'Thesis Writing',
  'Academic Visit',
  'Academic Exchange',
  'Cultural Exchange',
  'Facilities Exchange',
  'Staf/Faculty Exchange',
  'Joint Curriculum',
  'Credit Transfer',
  'Joint Lecturer/ Kuliah Bersama',
  'Joint Projects (Konferensi/Seminar/Workshop/Lomba/pameran)',
  'Joint Research',
  'Publikasi Jurnal Ilmiah',
  'Merdeka Belajar Kampus Merdeka (MBKM)',
  'Rekrutmen Lulusan',
  'Pengabdian Kepada Masyarakat/ Service Learning',
  'Beasiswa',
  'Hibah/Donasi',
  'Educational and Training Program',
  'Sertifikasi',
  'Akreditasi',
  'Program Sejong Korean',
  'Penerimaan mahasiswa baru',
  'Pemanfaatan e-AMITRA',
  'Penyelenggaraan Pusat Dukungan Teknologi dan Inovasi',
  'Penyelenggaraan IELTS Off-site Testing',
  'Penyelenggaraan Tax Center',
  'Pelaksanaan Asesor BKD Sertifikasi Dosen',
  'Pendayagunaan Aparatur Negara dan Pelaksanaan Reformasi Birokrasi',
  'Pemberdayaan dan pemanfaatan perpustakaan',
  'Website Bursa Informasi Pendidikan Tinggi (BIDikTi)',
  'Layanan Transaksi Online',
  'Asuransi',
  'Penyediaan Layanan Telekomunikasi',
  'Promosi Kegiatan',
  'Pembuatan Website',
  'Proyek pendukung untuk Penelitian',
  'Perjanjian Kerahasiaan',
  'Pelatihan Guru',
  'Pengembangan dan kerahasiaan layanan komputasi, server, perangkat lunak, penyimpanan data, database, dan jaringan modul digital dalam Platform LMS Gamifikasi',
  'Pengembangan modul digital ke dalam Platform LMS Gamifikasi',
  'Pemanfaatan LMS Gamifikasi sebagai medium pembelajaran di universitas masing-masing.',
  'Layanan Digital',
  'Pemanfaatan Sistem Pembelajaran Petraverse',
  'Pelatihan',
  'Program ODP (Officer Development Program)',
  'Product & Design Development Center',
  'Software Application Development Center',
  'Perlindungan anak, kesehatan masyarakat, sosial, ekonomi, lingkungan, kebencanaan',
  'Pelayanan pendaftaran HAKI pada lingkup sektor industri yang tersedia',
  'Pemanfaatan Vending Machine',
  'Joint Project (Pemberian Jasa)',
  'Pendirian Fakultas Kedokteran Gigi',
  'Adendum/Amandemen',
  'Online Course',
  'Program Darmasiswa',
  'Falling Walls Lab Indonesia',
  'Business Class with PBS',
  'Kegiatan Mata Kuliah Wajib Kurikulum (MKWK)',
  'Perekrutan mahasiswa',
  'Dual Degree'
 );
