-- Phase 3 — renewal: the second kind of disposition, the dual evaluation, the
-- four-outcome gate, the split override, and the Perpanjangan proposal.
--
-- The single rule this file exists to protect: a renewal request shares tables
-- with an approval but never shares logic. It has no tier, never enters
-- recompute_tiers, and gates nothing — it completes when the unit uploads the
-- draft (BR-24, BR-25). Every function below branches on jenis_disposisi before
-- anything else.

-- --------------------------------------------------------------------------
-- Who may act for a unit
-- --------------------------------------------------------------------------
-- A renewal request targets the owning unit's head position, but ANY account of
-- that unit may act on it (AR-08). Membership is subtree-shaped in both
-- directions: a Dekan acts for a prodi beneath them, and a prodi account acts
-- on a request addressed to the prodi.
create function akun_milik_unit(p_id_unit int) returns boolean
language sql stable security definer set search_path = public as $fn$
  with saya as (
    select j.id_unit from akun a join jabatan j on j.id = a.id_jabatan
     where a.id = current_akun_id()
  )
  select exists (select 1 from saya where id_unit = p_id_unit)
      or exists (select 1 from saya s
                  where p_id_unit in (select id from unit_descendants(s.id_unit)))
      or exists (select 1 from saya s
                  where s.id_unit in (select id from unit_descendants(p_id_unit)));
$fn$;

-- The positions that own an expiring document's relationship: its proposing
-- positions. A renewal request is routed to these (BR-25).
create function jabatan_pemilik_dokumen(p_no_dokumen int) returns setof int
language sql stable security definer set search_path = public as $fn$
  select pg.id_jabatan
    from dokumen_kerja_sama dk
    join pengusul pg on pg.id_proposal_dokumen = dk.id_proposal_dokumen
   where dk.no = p_no_dokumen;
$fn$;

create function token_baru() returns char(64)
language sql volatile set search_path = public as $fn$
  -- 256 bits. The token IS the credential, so it is generated by a CSPRNG and
  -- never from anything guessable such as a timestamp or an id (BR-30).
  select encode(extensions.gen_random_bytes(32), 'hex')::char(64);
$fn$;

-- --------------------------------------------------------------------------
-- The renewal request
-- --------------------------------------------------------------------------
-- Dispositioned by the Head of IO when a document nears expiry. Its payload is
-- the expiring document plus both evaluations, so both are created here and the
-- partner's token link exists from the moment the unit opens the task.
create function kirim_permintaan_pembaruan(p_no_dokumen int, p_pesan text default null)
returns int
language plpgsql security definer set search_path = public as $fn$
declare
  v_no_disposisi int;
  v_jabatan int;
  v_ada boolean := false;
  v_no_eval int;
  v_id_kontak int;
begin
  if not current_akun_is_io() then
    raise exception 'Only IO dispositions a renewal request (PRD §9.1)';
  end if;

  if exists (select 1 from disposisi
              where no_dokumen_kerjasama = p_no_dokumen
                and jenis_disposisi = 'renewal_request') then
    raise exception 'Document % already has a renewal request', p_no_dokumen;
  end if;

  insert into disposisi (no_dokumen_kerjasama, jenis_disposisi, round_ke,
                         pesan_disposisi, id_akun_pengirim)
  values (p_no_dokumen, 'renewal_request', 1,
          coalesce(p_pesan, 'Mohon ditangani pembaruan dokumen ini.'),
          current_akun_id())
  returning no into v_no_disposisi;

  -- No tier, and open immediately: there is nothing below it to wait for,
  -- because a renewal request gates nothing (BR-24). Its deadline runs on the
  -- 30/60/90 CALENDAR-day scale, never the approval scale (BR-32).
  for v_jabatan in select * from jabatan_pemilik_dokumen(p_no_dokumen) loop
    insert into disposisi_target (no_disposisi, id_jabatan, tier, status,
                                  waktu_unlock, batas_waktu_sla, status_sla)
    values (v_no_disposisi, v_jabatan, null, 'pending_action', now(),
            now() + (pengaturan('renewal_red_days','90') || ' days')::interval,
            'normal');
    v_ada := true;
  end loop;

  if not v_ada then
    raise exception 'Document % has no proposing position to route the renewal to', p_no_dokumen;
  end if;

  -- The faculty evaluation, filled in-system by any account of the unit.
  insert into evaluasi (id_dokumen_kerjasama, respondent_type, status)
  values (p_no_dokumen, 'faculty', 'pending');

  -- The partner evaluation: one, for the LEAD partner, even when the document
  -- has several (BR-29).
  select pc.id into v_id_kontak
    from dokumen_kerja_sama dk
    join partner_pengusul pp on pp.id_proposal_dokumen = dk.id_proposal_dokumen
    join partner pr on pr.id = pp.id_partner
    left join partner_contact pc on pc.id = pr.id_partner_contact
   where dk.no = p_no_dokumen
   order by pp.is_lead desc
   limit 1;

  insert into evaluasi (id_dokumen_kerjasama, respondent_type, status, id_partner_contact)
  values (p_no_dokumen, 'partner', 'pending', v_id_kontak)
  returning no into v_no_eval;

  insert into partner_eval_token (id_evaluasi, token, id_akun_pengirim)
  values (v_no_eval, token_baru(), current_akun_id());

  return v_no_disposisi;
end;
$fn$;

-- --------------------------------------------------------------------------
-- The gate and its four outcomes (PRD §9.4)
-- --------------------------------------------------------------------------
-- Returns menunggu / terbuka / terminate / split.
--
-- "Submitted AND continue" is checked explicitly on both sides. A NULL
-- recommendation is not a continue, and an unsubmitted evaluation is not a
-- recommendation at all — the one way this gate gets built wrong is by letting
-- a NULL fall through as agreement (BR-26).
create function status_gerbang_pembaruan(p_no_dokumen int) returns text
language plpgsql stable security definer set search_path = public as $fn$
declare
  v_fak text;
  v_mitra text;
  v_override text;
begin
  -- The latest non-superseded answer per side; a reopened evaluation replaces
  -- its predecessor without editing it (DR-08).
  select rekomendasi into v_fak from evaluasi
   where id_dokumen_kerjasama = p_no_dokumen and respondent_type = 'faculty'
     and status = 'submitted'
   order by no desc limit 1;

  select rekomendasi into v_mitra from evaluasi
   where id_dokumen_kerjasama = p_no_dokumen and respondent_type = 'partner'
     and status = 'submitted'
   order by no desc limit 1;

  if v_fak is null or v_mitra is null then
    return 'menunggu';
  end if;

  if v_fak = 'continue' and v_mitra = 'continue' then
    return 'terbuka';
  end if;

  if v_fak = 'terminate' and v_mitra = 'terminate' then
    return 'terminate';
  end if;

  -- They disagree. Nothing resolves automatically: it waits for a recorded,
  -- reasoned override (BR-27).
  select keputusan into v_override from keputusan_pembaruan
   where id_dokumen_kerjasama = p_no_dokumen
   order by id desc limit 1;

  if v_override = 'continue' then return 'terbuka'; end if;
  if v_override = 'terminate' then return 'terminate'; end if;
  return 'split';
end;
$fn$;

-- The split override. The reason is required — that is the entire point of
-- recording the decision rather than letting IO simply proceed.
create function putuskan_pembaruan(p_no_dokumen int, p_keputusan text, p_alasan text)
returns void
language plpgsql security definer set search_path = public as $fn$
begin
  if not current_akun_is_io() then
    raise exception 'Only IO or the Head resolves a split decision (PRD §4.2)';
  end if;
  if p_keputusan not in ('continue','terminate') then
    raise exception 'A split is resolved as continue or terminate, not %', p_keputusan;
  end if;
  if coalesce(btrim(p_alasan), '') = '' then
    raise exception 'A split-decision override requires a reason (BR-27)';
  end if;
  if status_gerbang_pembaruan(p_no_dokumen) <> 'split' then
    raise exception 'Document % is not in a split decision', p_no_dokumen;
  end if;

  insert into keputusan_pembaruan (id_dokumen_kerjasama, keputusan, alasan, id_akun)
  values (p_no_dokumen, p_keputusan, p_alasan, current_akun_id());
end;
$fn$;

-- --------------------------------------------------------------------------
-- Submitting an evaluation
-- --------------------------------------------------------------------------
-- Both sides answer the same five dimensions on the same 1-5 scale, so the two
-- grids are comparable; one writer, so they cannot drift apart. The Likert
-- range and the recommendation vocabulary are enforced by the column checks —
-- this is a trust boundary on the partner side, where the caller is the public
-- internet.
--
-- form_revision is deliberately untouched: it is frozen per submission, so a
-- later change to the form never migrates an old answer (BR-31).
create function terapkan_jawaban_evaluasi(p_no int, p_jawaban jsonb) returns void
language plpgsql security definer set search_path = public as $fn$
begin
  if (p_jawaban ->> 'rekomendasi') not in ('continue','terminate') then
    raise exception 'A recommendation must be continue or terminate';
  end if;

  update evaluasi set
    exp_quality        = (p_jawaban ->> 'exp_quality')::smallint,
    exp_relevance      = (p_jawaban ->> 'exp_relevance')::smallint,
    exp_productivity   = (p_jawaban ->> 'exp_productivity')::smallint,
    exp_sustainability = (p_jawaban ->> 'exp_sustainability')::smallint,
    exp_communication  = (p_jawaban ->> 'exp_communication')::smallint,
    sat_quality        = (p_jawaban ->> 'sat_quality')::smallint,
    sat_relevance      = (p_jawaban ->> 'sat_relevance')::smallint,
    sat_productivity   = (p_jawaban ->> 'sat_productivity')::smallint,
    sat_sustainability = (p_jawaban ->> 'sat_sustainability')::smallint,
    sat_communication  = (p_jawaban ->> 'sat_communication')::smallint,
    rekomendasi        = p_jawaban ->> 'rekomendasi',
    continuation_mode  = nullif(p_jawaban ->> 'continuation_mode', ''),
    catatan_evaluasi   = nullif(p_jawaban ->> 'catatan_evaluasi', ''),
    respondent_nama    = coalesce(nullif(p_jawaban ->> 'respondent_nama', ''), respondent_nama),
    respondent_email   = coalesce(nullif(p_jawaban ->> 'respondent_email', ''), respondent_email),
    status             = 'submitted',
    waktu_evaluasi     = now()
  where no = p_no and status = 'pending';

  if not found then
    raise exception 'Evaluation % is not awaiting an answer', p_no;
  end if;
end;
$fn$;

-- Faculty side: in-system, by any account of the owning unit (AR-08).
create function kirim_evaluasi_fakultas(p_no int, p_jawaban jsonb) returns void
language plpgsql security definer set search_path = public as $fn$
declare v_unit int; v_jabatan int;
begin
  select j.id_unit into v_unit
    from evaluasi e
    join dokumen_kerja_sama dk on dk.no = e.id_dokumen_kerjasama
    join pengusul pg on pg.id_proposal_dokumen = dk.id_proposal_dokumen
    join jabatan j on j.id = pg.id_jabatan
   where e.no = p_no and e.respondent_type = 'faculty'
   limit 1;

  if v_unit is null then
    raise exception 'Evaluation % is not a faculty evaluation', p_no;
  end if;
  if not (current_akun_is_io() or akun_milik_unit(v_unit)) then
    raise exception 'Only an account of the owning unit fills this evaluation (AR-08)';
  end if;

  select id_jabatan into v_jabatan from akun where id = current_akun_id();
  update evaluasi set id_jabatan_pengusul = v_jabatan where no = p_no;

  perform terapkan_jawaban_evaluasi(p_no, p_jawaban);

  insert into notifikasi (jenis_notifikasi, id_jabatan_penerima, no_dokumen_kerjasama, isi, status)
  select 'evaluation_submitted', io, e.id_dokumen_kerjasama,
         'Evaluasi fakultas telah masuk.', 'pending'
    from evaluasi e, jabatan_io() io where e.no = p_no;
end;
$fn$;

-- --------------------------------------------------------------------------
-- The partner's no-login path
-- --------------------------------------------------------------------------
-- Deviation from Architecture §9, taken deliberately: the token resolves in a
-- Postgres function granted to `anon` rather than in an Edge Function on the
-- service role. The security property is the same — server-side resolution,
-- scoped to exactly one evaluation, exposing nothing else — and it removes a
-- deployment surface and one more copy of the service-role key. `anon` can
-- execute exactly these two functions and nothing else in the schema.
--
-- The token is the credential: valid until submitted, then inert (BR-30).
create function resolusi_token_evaluasi(p_token text) returns jsonb
language plpgsql stable security definer set search_path = public as $fn$
declare v jsonb;
begin
  select jsonb_build_object(
           'no_evaluasi',   e.no,
           'status',        e.status,
           'nama_mitra',    pr.nama,
           'negara',        n.nama,
           'nama_kontak',   pc.nama,
           'email_kontak',  pc.email,
           'no_dokumen',    dk.no_dokumen,
           'jenis',         p.jenis_kerjasama,
           'tanggal_mulai', dk.tanggal_mulai,
           'tanggal_berakhir', dk.tanggal_berakhir,
           'form_revision', e.form_revision)
    into v
    from partner_eval_token t
    join evaluasi e on e.no = t.id_evaluasi
    join dokumen_kerja_sama dk on dk.no = e.id_dokumen_kerjasama
    join proposal_dokumen p on p.id = dk.id_proposal_dokumen
    left join partner_pengusul pp
           on pp.id_proposal_dokumen = p.id and pp.is_lead
    left join partner pr on pr.id = pp.id_partner
    left join negara n on n.id = pr.id_negara
    left join partner_contact pc on pc.id = e.id_partner_contact
   where t.token = p_token and t.is_active;

  -- Nothing about the document's internals, no lists, and nothing at all for a
  -- token that does not resolve (AR-07).
  return v;
end;
$fn$;

create function kirim_evaluasi_partner(p_token text, p_jawaban jsonb) returns void
language plpgsql security definer set search_path = public as $fn$
declare v_no int;
begin
  select e.no into v_no
    from partner_eval_token t join evaluasi e on e.no = t.id_evaluasi
   where t.token = p_token and t.is_active and e.status = 'pending';

  if v_no is null then
    raise exception 'Tautan evaluasi ini tidak berlaku atau sudah terisi.';
  end if;

  -- Name and email are the accountability record for a form with no login, so
  -- they are required here rather than merely asked for (PRD §9.3).
  if coalesce(btrim(p_jawaban ->> 'respondent_nama'), '') = ''
     or coalesce(btrim(p_jawaban ->> 'respondent_email'), '') = '' then
    raise exception 'Nama dan email responden wajib diisi.';
  end if;

  perform terapkan_jawaban_evaluasi(v_no, p_jawaban);

  -- Submitted, so the token goes inert. Only a recorded reopen brings it back.
  update partner_eval_token
     set waktu_submit = now(), is_active = false
   where token = p_token;

  insert into notifikasi (jenis_notifikasi, id_jabatan_penerima, no_dokumen_kerjasama, isi, status)
  select 'evaluation_submitted', io, e.id_dokumen_kerjasama,
         'Evaluasi mitra telah masuk.', 'pending'
    from evaluasi e, jabatan_io() io where e.no = v_no;

  -- A disagreement is flagged the moment it becomes one, not at the next sweep.
  insert into notifikasi (jenis_notifikasi, id_jabatan_penerima, no_dokumen_kerjasama, isi, status)
  select 'split_decision', io, e.id_dokumen_kerjasama,
         'Evaluasi fakultas dan mitra berbeda — perlu keputusan dengan alasan.', 'pending'
    from evaluasi e, jabatan_io() io
   where e.no = v_no and status_gerbang_pembaruan(e.id_dokumen_kerjasama) = 'split';
end;
$fn$;

-- Reopening supersedes; it never edits. The prior answer stays exactly as it
-- was submitted, a fresh pending row takes its place, and a new token is issued
-- — so a change of mind has a recorded path (BR-30, DR-08).
create function buka_ulang_evaluasi(p_no int) returns text
language plpgsql security definer set search_path = public as $fn$
declare v_lama evaluasi; v_baru int; v_token text;
begin
  if not current_akun_is_io() then
    raise exception 'Only IO or the Head reopens an evaluation (PRD §9.5)';
  end if;

  select * into v_lama from evaluasi where no = p_no;
  if not found then raise exception 'Evaluation % does not exist', p_no; end if;
  if v_lama.status <> 'submitted' then
    raise exception 'Only a submitted evaluation can be reopened; this one is %', v_lama.status;
  end if;

  update evaluasi set status = 'superseded' where no = p_no;

  insert into evaluasi (id_dokumen_kerjasama, respondent_type, id_partner_contact,
                        id_jabatan_pengusul, form_revision, status, id_supersedes)
  values (v_lama.id_dokumen_kerjasama, v_lama.respondent_type, v_lama.id_partner_contact,
          v_lama.id_jabatan_pengusul, v_lama.form_revision, 'pending', p_no)
  returning no into v_baru;

  if v_lama.respondent_type = 'partner' then
    update partner_eval_token
       set is_active = false, waktu_reopen = now(), id_akun_reopen = current_akun_id()
     where id_evaluasi = p_no;

    v_token := token_baru();
    insert into partner_eval_token (id_evaluasi, token, id_akun_pengirim)
    values (v_baru, v_token, current_akun_id());
  end if;

  return v_token;
end;
$fn$;

-- --------------------------------------------------------------------------
-- The Perpanjangan proposal
-- --------------------------------------------------------------------------
-- The gate is enforced HERE, server-side, and cannot be bypassed by any route:
-- a missing evaluation or a single "terminate" simply refuses (BR-26).
create function buat_proposal_perpanjangan(p_no_dokumen int, p_file text default null)
returns int
language plpgsql security definer set search_path = public as $fn$
declare
  v_gerbang text;
  v_lama proposal_dokumen;
  v_baru int;
  v_unit int;
begin
  v_gerbang := status_gerbang_pembaruan(p_no_dokumen);
  if v_gerbang <> 'terbuka' then
    raise exception
      'Pembaruan belum dapat diajukan: gerbang evaluasi berstatus %. Kedua evaluasi harus masuk dan keduanya merekomendasikan lanjut (BR-26).',
      v_gerbang;
  end if;

  select p.* into v_lama
    from dokumen_kerja_sama dk join proposal_dokumen p on p.id = dk.id_proposal_dokumen
   where dk.no = p_no_dokumen;

  select j.id_unit into v_unit
    from pengusul pg join jabatan j on j.id = pg.id_jabatan
   where pg.id_proposal_dokumen = v_lama.id limit 1;

  if not (current_akun_is_io() or akun_milik_unit(v_unit)) then
    raise exception 'Only an account of the owning unit uploads the renewal draft (AR-08)';
  end if;

  -- The predecessor link IS the renewal flag; there is no second boolean.
  insert into proposal_dokumen (
    jenis_kerjasama, periode_kerjasama, sifat_periode_kerjasama, status_proposal,
    tujuan_kerjasama, manfaat_bagi_petra, manfaat_bagi_mitra, informasi_tambahan,
    file_draft, id_dokumen_sebelumnya, id_akun_pembuat, waktu_proposal_dokumen)
  values (
    v_lama.jenis_kerjasama, v_lama.periode_kerjasama, v_lama.sifat_periode_kerjasama,
    'Diajukan', v_lama.tujuan_kerjasama, v_lama.manfaat_bagi_petra,
    v_lama.manfaat_bagi_mitra, v_lama.informasi_tambahan,
    p_file, v_lama.id, current_akun_id(), now())
  returning id into v_baru;

  -- Everything that describes the partnership carries over; only the approval
  -- itself starts again.
  insert into partner_pengusul (id_partner, id_proposal_dokumen, is_lead)
  select id_partner, v_baru, is_lead from partner_pengusul where id_proposal_dokumen = v_lama.id;
  insert into pengusul (id_jabatan, id_proposal_dokumen)
  select id_jabatan, v_baru from pengusul where id_proposal_dokumen = v_lama.id;
  insert into proposal_dokumen_agenda (id_proposal_dokumen, id_agenda)
  select v_baru, id_agenda from proposal_dokumen_agenda where id_proposal_dokumen = v_lama.id;
  insert into proposal_dokumen_bidang (id_proposal_dokumen, id_bidang_kerjasama)
  select v_baru, id_bidang_kerjasama from proposal_dokumen_bidang where id_proposal_dokumen = v_lama.id;
  insert into proposal_dokumen_unit (id_proposal_dokumen, id_unit)
  select v_baru, id_unit from proposal_dokumen_unit where id_proposal_dokumen = v_lama.id;

  insert into proposal_dokumen_mou (id_proposal_dokumen, ringkasan_kegiatan)
  select v_baru, ringkasan_kegiatan from proposal_dokumen_mou where id_proposal_dokumen = v_lama.id;
  insert into proposal_dokumen_moa (id_proposal_dokumen, hak_petra, hak_calon_mitra,
                                    kewajiban_petra, kewajiban_calon_mitra)
  select v_baru, hak_petra, hak_calon_mitra, kewajiban_petra, kewajiban_calon_mitra
    from proposal_dokumen_moa where id_proposal_dokumen = v_lama.id;

  -- The renewal request completes by the draft arriving — not by an approve or
  -- a reject, which it never had (BR-25).
  update disposisi_target dt
     set status = 'approved', waktu_resolusi = now()
    from disposisi d
   where d.no = dt.no_disposisi
     and d.no_dokumen_kerjasama = p_no_dokumen
     and d.jenis_disposisi = 'renewal_request'
     and dt.status = 'pending_action';

  insert into riwayat_approval (id_proposal_dokumen, id_akun, aksi, catatan)
  values (v_baru, current_akun_id(), 'submitted',
          'Draf pembaruan diunggah oleh unit pemilik; proposal Perpanjangan dibuat.');

  return v_baru;
end;
$fn$;

-- The approver list a renewal starts from: the positions that approved the
-- predecessor. Empty for a legacy document with no approval history, which is
-- correct — there is nothing to prefill from (PRD §9.6).
create function jabatan_prefill_perpanjangan(p_id_proposal int) returns setof int
language sql stable security definer set search_path = public as $fn$
  select distinct dt.id_jabatan
    from proposal_dokumen p
    join disposisi d on d.id_proposal_dokumen = p.id_dokumen_sebelumnya
                    and d.jenis_disposisi = 'approval'
    join disposisi_target dt on dt.no_disposisi = d.no
   where p.id = p_id_proposal and dt.status = 'approved';
$fn$;

-- --------------------------------------------------------------------------
-- Two existing functions gain their renewal behaviour
-- --------------------------------------------------------------------------

-- On a Perpanjangan, the uploader's own position is auto-approved — but only if
-- it is actually in the list IO sent (PRD §9.6). Everything else about sending
-- a disposition is unchanged.
create or replace function kirim_disposisi(p_id_proposal int, p_id_jabatan int[],
                                           p_pesan text default null,
                                           p_lampiran text default null)
returns int
language plpgsql security definer set search_path = public as $fn$
declare
  v_no_disposisi int; v_round int; v_jabatan int; v_tier smallint;
  v_perpanjangan boolean; v_jabatan_pengunggah int; v_no_target int;
begin
  if not current_akun_is_io() then
    raise exception 'Only IO assigns dispositions';
  end if;
  if coalesce(array_length(p_id_jabatan, 1), 0) = 0 then
    raise exception 'A disposition needs at least one target position';
  end if;

  select coalesce(max(round_ke), 1) into v_round from disposisi
   where id_proposal_dokumen = p_id_proposal and jenis_disposisi = 'approval';

  select p.id_dokumen_sebelumnya is not null, a.id_jabatan
    into v_perpanjangan, v_jabatan_pengunggah
    from proposal_dokumen p join akun a on a.id = p.id_akun_pembuat
   where p.id = p_id_proposal;

  insert into disposisi (id_proposal_dokumen, jenis_disposisi, round_ke,
                         pesan_disposisi, lampiran, id_akun_pengirim)
  values (p_id_proposal, 'approval', v_round, p_pesan, p_lampiran, current_akun_id())
  returning no into v_no_disposisi;

  foreach v_jabatan in array p_id_jabatan loop
    select tier_disposisi into v_tier from jabatan where id = v_jabatan;
    if v_tier is null then
      raise exception 'Position % has no approval tier; it cannot be an approver (BR-15)', v_jabatan;
    end if;
    insert into disposisi_target (no_disposisi, id_jabatan, tier, status)
    values (v_no_disposisi, v_jabatan, v_tier, 'waiting')
    returning no into v_no_target;

    if v_perpanjangan and v_jabatan = v_jabatan_pengunggah then
      update disposisi_target
         set status = 'approved', waktu_resolusi = now(), durasi_hari_kerja = 0,
             status_sla = 'normal'
       where no = v_no_target;

      insert into riwayat_approval (id_disposisi_target, id_proposal_dokumen, id_akun, aksi, catatan)
      values (v_no_target, p_id_proposal, current_akun_id(), 'approve',
              'Disetujui otomatis: jabatan ini yang mengunggah draf pembaruan (PRD §9.6).');
    end if;
  end loop;

  insert into riwayat_approval (id_proposal_dokumen, id_akun, aksi, catatan)
  values (p_id_proposal, current_akun_id(), 'dispositioned', p_pesan);

  perform recompute_tiers(p_id_proposal);
  return v_no_disposisi;
end;
$fn$;

-- Activation now closes the renewal chain in the same transaction that opens
-- the successor: link, archive the predecessor with its reason, done. Partially
-- linking a renewal is the failure mode this prevents (BR-12).
create or replace function aktivasi_dokumen(
  p_id_proposal          int,
  p_no_dokumen           text,
  p_tanggal_tanda_tangan date,
  p_tanggal_mulai        date,
  p_tanggal_berakhir     date default null,
  p_folder_kui           text default null,
  p_no_berkas_dikti      text default null,
  p_upload_dokumen       text default null
) returns int
language plpgsql security definer set search_path = public as $fn$
declare v_no int; v_sebelumnya int;
begin
  if not current_akun_is_io() then
    raise exception 'Only IO activates a document';
  end if;
  if (select status_proposal from proposal_dokumen where id = p_id_proposal) <> 'Disetujui' then
    raise exception 'Only a fully approved proposal can be activated';
  end if;

  insert into dokumen_kerja_sama (
    id_proposal_dokumen, no_dokumen, tanggal_tanda_tangan, tanggal_mulai,
    tanggal_berakhir, status, folder_kui, no_berkas_dikti, upload_dokumen)
  values (
    p_id_proposal, p_no_dokumen, p_tanggal_tanda_tangan, p_tanggal_mulai,
    p_tanggal_berakhir, 'Aktif', p_folder_kui, p_no_berkas_dikti, p_upload_dokumen)
  returning no into v_no;

  update proposal_dokumen set waktu_aktif = now() where id = p_id_proposal;

  select id_dokumen_sebelumnya into v_sebelumnya
    from proposal_dokumen where id = p_id_proposal;

  if v_sebelumnya is not null then
    update dokumen_kerja_sama
       set status = 'Diarsipkan', alasan_arsip = 'superseded_by_renewal'
     where id_proposal_dokumen = v_sebelumnya;

    insert into riwayat_approval (id_proposal_dokumen, id_akun, aksi, catatan)
    values (v_sebelumnya, current_akun_id(), 'archived',
            'superseded_by_renewal — digantikan oleh dokumen ' || p_no_dokumen);
    -- Any future Implementation Arrangement transfers to the successor here;
    -- the Realization System's table does not exist yet (Phase 4).
  end if;

  insert into riwayat_approval (id_proposal_dokumen, id_akun, aksi, catatan)
  values (p_id_proposal, current_akun_id(), 'activated', p_no_dokumen);

  return v_no;
end;
$fn$;

-- --------------------------------------------------------------------------
-- Grants
-- --------------------------------------------------------------------------
grant execute on function akun_milik_unit(int)                    to authenticated;
grant execute on function jabatan_pemilik_dokumen(int)            to authenticated;
grant execute on function kirim_permintaan_pembaruan(int, text)   to authenticated;
grant execute on function status_gerbang_pembaruan(int)           to authenticated;
grant execute on function putuskan_pembaruan(int, text, text)     to authenticated;
grant execute on function kirim_evaluasi_fakultas(int, jsonb)     to authenticated;
grant execute on function buka_ulang_evaluasi(int)                to authenticated;
grant execute on function buat_proposal_perpanjangan(int, text)   to authenticated;
grant execute on function jabatan_prefill_perpanjangan(int)       to authenticated;

-- The only two things `anon` may execute in the entire schema. Both require a
-- 256-bit token and both are scoped to exactly one evaluation (AR-07).
grant execute on function resolusi_token_evaluasi(text) to anon, authenticated;
grant execute on function kirim_evaluasi_partner(text, jsonb) to anon, authenticated;

-- Internal: called only by the two submit functions, which check authority.
revoke execute on function terapkan_jawaban_evaluasi(int, jsonb)
  from public, anon, authenticated;
revoke execute on function token_baru() from public, anon, authenticated;

comment on function status_gerbang_pembaruan is
  'menunggu / terbuka / terminate / split. A NULL recommendation is never a
   continue and an unsubmitted evaluation is never a recommendation (BR-26).';
